version: '3'

services:
        app:
                build:  .
                container_name: app
                entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
                environment: 
                        - DB_HOST=db
                        - DB_DATABASE=laravel
                        - DB_USERNAME=root
                        - DB_PASSWORD=root
                volumes:
                        - .:/var/www
                networks: 
                        - app-network
                depends_on:
                        - db
                        - redis
                        # - nginx
                        # condition: service_healthy
                                
        nginx:
                build: .docker/nginx
                container_name: nginx
                restart: always
                tty: true
                ports:
                    - "8000:80"
                volumes: 
                    - .:/var/www   
                networks: 
                    - app-network
        db:
                image: mysql:5.7
                command: --innodb-use-native-aio=0
                container_name: db
                restart: always
                tty: true
                ports:
                    - "33006:3306"
                environment: 
                        - MYSQL_DATABASE=laravel
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_USER=root
                volumes: 
                    - ./.docker/dbdata:/var/lib/mysql
                networks: 
                    - app-network
        #         # healthcheck:
        #         #         test: ["CMD-SHELL", 'mysql -uroot --database=laravel --password=root --executes="SELECT count(table_name)> 0 FROM information_schema.tables;" --skip-column-names -B']  
        #         #         interval: 10s
        #         #         timeout: 10s
        #         #         retries: 4
        redis:
                image: redis:alpine
                expose:
                    - 6379
                networks: 
                    - app-network

networks:
        app-network:
                driver: bridge
